trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  solution: 'src/Server/BettingSystem.sln'

steps:
- task: NuGetToolInstaller@1
  displayName: Install NuGet

- task: UseDotNet@2
  displayName: 'Install .NET 6'
  inputs:
    packageType: sdk
    version: '6.0.x'

- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: restore
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'
  
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: 'src/Server/*/*.csproj'
    arguments: '--configuration Debug'
